### ISSUE TITLE
It is not an issue. 

### ISSUE THREAD

**Issue by arturmaj** [harperreed/google-home-notifier-python#3]
Thanks Harper for Obama... and the interface.
The main.py runs ok no errors but I am not getting a sound from the Google Home. Except the first time when lounching app CC1AD845 I can hear the short "ploom".
My log:
ARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 318-290-727
INFO:root:http://eee:5000/static/cache/co-tam-sie-dzieje-pl-false.mp3
http://eee:5000/static/cache/co-tam-sie-dzieje-pl-false.mp3
INFO:pychromecast.controllers:Receiver:Launching app CC1AD845
INFO:werkzeug:192.168.90.2 - - [13/Oct/2017 15:26:09] "GET /say/?text=%22co%20tam%20sie%20dzieje%22&lang=pl HTTP/1.1" 200 -
INFO:root:http://eee:5000/static/cache/co-tam-sie-dzieje-pl-false.mp3
http://eee:5000/static/cache/co-tam-sie-dzieje-pl-false.mp3
INFO:pychromecast.controllers:Not launching app CC1AD845 - already running
INFO:werkzeug:192.168.90.2 - - [13/Oct/2017 15:26:22] "GET /say/?text=%22co%20tam%20sie%20dzieje%22&lang=pl HTTP/1.1" 200 -
Play mp3 behaves the same.

**Comment by AndyAtos** [comment]
Hi arturmaj,
I had a very similar issue - in my case it turned out that my local firewall was blocking port 5000 so the Google device couldn't retrieve the cached media file. 

A

**Comment by SergioML9** [comment]
Hi,

I had the same issue and I have solved it accessing to the service with the ip of the machine where I have launched the script, instead of accessing to 0.0.0.0.

**Comment by abdulrahman004** [comment]
For me Sergio's solution worked. replaced 0.0.0.0 with local IP
the port thing wasnt a problem

**Comment by P4Thi0ut** [comment]
Just in case you are in the same situation just replace the mp3_url of method play_mp3 with the mp3 from the git repo : https://raw.githubusercontent.com/harperreed/google-home-notifier-python/master/static/doorbell1.mp3, in the main.py. If you here the bell it means the Google Home can't reach your local mp3 file for a reason. Hope it helps for debug !

**Comment by noisufnoc** [comment]
hey @P4Thi0ut this was really helpful in debugging.
